import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nate Croteau | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nate Croteau
        </h1>

        <p className={styles.description}>

        </p>

        <div className={styles.grid}>

        </div>
      </main>

    </div>
  )
}
